### ISSUE TITLE
默认开启了水纹在项目中会崩溃

### ISSUE THREAD

**Issue by isunkui** [tianzhijiexian/SelectorInjection#3]
#### 整合进我的项目时候，默认开启了水纹在项目中会崩溃
- 必须手动在布局文件中将showRipple置为false，才正常使用（跑demo工程没有这个问题）。
- **布局中设置了android:enabled="true"， 也会导致程序崩溃**

`手机：小米note`
`miui版本：miui7 6.5.12`
`android版本：6.0.1`

``` java
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/item_background_material.xml from color state list resource ID #0x1080457
    at android.content.res.Resources.loadColorStateListForCookie(Resources.java:2800)
    at android.content.res.Resources.loadColorStateList(Resources.java:2749)
    at android.content.res.TypedArray.getColorStateList(TypedArray.java:487)
    at android.graphics.drawable.RippleDrawable.updateStateFromTypedArray(RippleDrawable.java:473)
    at android.graphics.drawable.RippleDrawable.applyTheme(RippleDrawable.java:517)
    at android.content.res.Resources.loadDrawable(Resources.java:2589)
    at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:387)
    at android.content.res.Resources.getDrawable(Resources.java:824)
    at android.content.Context.getDrawable(Context.java:458)
    at kale.injection.SelectorInjection.setSelector(SelectorInjection.java:161)
    at kale.injection.SelectorInjection.injection(SelectorInjection.java:148)
    at kale.ui.view.SelectorTextView.<init>(SelectorTextView.java:25)
    at kale.ui.view.SelectorTextView.<init>(SelectorTextView.java:19)
    ... 30 more
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid color state list tag ripple
    at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java:217)
    at android.content.res.ColorStateList.createFromXml(ColorStateList.java:201)
    at android.content.res.Resources.loadColorStateListForCookie(Resources.java:2796)
    ... 42 more
```

**Comment by kaleai** [comment]
我也发现了这个问题了，我会快速修复，目前暂时解决方案是关闭水波纹。我在研究原因，感谢你的反馈

**Comment by kaleai** [comment]
这个问题我看了一下，是因为你没有在theme中提供默认的水波纹颜色。我的demo里面是增加了：

<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:selectableItemBackground">@color/material_grey_600</item>
    </style>

你提出的问题很多人也可能遇到，所以我可能会去掉这个默认的颜色选项。

**Comment by kaleai** [comment]
已经更新了一个版本，你看下是否修复了这个问题

**Comment by kaleai** [comment]
这个问题是没有添加必要属性引起的，我已经取消了这个强制属性。
